chore: bump urllib3 from 1.26.19 to 2.5.0 in /tests
Bumps [urllib3](https://github.com/urllib3/urllib3) from 1.26.19 to 2.5.0.
- [Release notes](https://github.com/urllib3/urllib3/releases)
- [Changelog](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst)
- [Commits](https://github.com/urllib3/urllib3/compare/1.26.19...2.5.0)

---
updated-dependencies:
- dependency-name: urllib3
  dependency-version: 2.5.0
  dependency-type: indirect
...

Install awscli2 because of
`ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'`
See https://github.com/aws/aws-cli/issues/7905

Co-authored-by: dependabot[bot] <support@github.com>
Signed-off-by: Daniel Skinstad Drabitzius <daniel.drabitzius@northern.tech>